# Generated by Django 4.0.4 on 2022-06-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_fest', '0002_rename_conocidos_organizadores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizadores',
            old_name='Puesto',
            new_name='puesto',
        ),
    ]
