# Generated by Django 4.0.4 on 2022-06-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro_fest', '0003_rename_puesto_organizadores_puesto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigos',
            old_name='edad',
            new_name='cuit',
        ),
        migrations.RenameField(
            model_name='amigos',
            old_name='puesto',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='punto_de_venta',
            old_name='puesto',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='punto_de_venta',
            old_name='edad',
            new_name='dni',
        ),
    ]
